-- =============================================================================
-- TVS Nepal Ride Operations - 2026/2027 Annual Calendar Seed
-- Source: Annual Ride calendar.xlsx
-- Run in: Supabase Dashboard → SQL Editor
-- Safe to re-run: uses ON CONFLICT (slug) DO UPDATE
-- =============================================================================

INSERT INTO rides (
  title, slug, community, ride_type, chapter,
  start_date, end_date, status, priority,
  short_description, description,
  expected_riders, tags,
  is_featured, is_recurring
) VALUES
  ('AOG Chapter Ride - Bagmati (May)', 'aog-chapter-ride-bagmati-may', 'AOG'::community_type, 'chapter'::ride_type, 'Bagmati'::chapter_name,
   '2026-05-09', '2026-05-09', 'completed'::ride_status, 'chapter'::ride_priority,
   'Monthly AOG chapter ride for Bagmati members.',
   'Regular monthly chapter ride for Apache Owners Group Bagmati chapter members.',
   20, ARRAY['aog', 'chapter', 'bagmati']::text[],
   false, false),
  ('CULT Ride - Bagmati (May)', 'cult-ride-bagmati-may', 'CULT'::community_type, 'cult'::ride_type, 'Bagmati'::chapter_name,
   '2026-05-23', '2026-05-23', 'completed'::ride_status, 'chapter'::ride_priority,
   'CULT community lifestyle and exploration ride.',
   'Monthly CULT ride focused on travel, lifestyle, and exploration for the Bagmati community.',
   20, ARRAY['cult', 'bagmati']::text[],
   false, false),
  ('AOG Ride - Dhangadhi', 'aog-ride-dhangadhi', 'AOG'::community_type, 'chapter'::ride_type, 'Mahakali'::chapter_name,
   '2026-06-06', '2026-06-06', 'planned'::ride_status, 'chapter'::ride_priority,
   'AOG chapter ride to Dhangadhi, far-western Nepal.',
   'AOG community ride to Dhangadhi (Kailali district), exploring the far-western corridor with chapter members.',
   20, ARRAY['aog', 'dhangadhi', 'far-west', 'mahakali']::text[],
   false, false),
  ('AOG Ride - Lumbini & Palpa', 'aog-ride-lumbini-palpa', 'AOG'::community_type, 'chapter'::ride_type, 'Lumbini'::chapter_name,
   '2026-06-13', '2026-06-13', 'planned'::ride_status, 'chapter'::ride_priority,
   'AOG chapter ride through Lumbini and Palpa.',
   'AOG chapter ride through the historic Lumbini province, with a route through Palpa (Tansen) hill town.',
   20, ARRAY['aog', 'lumbini', 'palpa', 'heritage']::text[],
   false, false),
  ('CULT Overnight - Dhorpatan', 'cult-overnight-dhorpatan', 'CULT'::community_type, 'overnight'::ride_type, 'Gandaki'::chapter_name,
   '2026-06-26', '2026-06-28', 'planned'::ride_status, 'chapter'::ride_priority,
   '3-day CULT ride into the Dhorpatan Hunting Reserve.',
   'A 3-day CULT overnight adventure into Dhorpatan - one of Nepal''s most remote and scenic destinations in Baglung district, Gandaki province. High-altitude passes, pristine trails, and wildlife.',
   30, ARRAY['cult', 'dhorpatan', 'overnight', 'gandaki', 'nature']::text[],
   false, false),
  ('AOG Community Ride - Bheri (Kohalpur/Nepalgunj)', 'aog-community-ride-bheri-kohalpurnepalgunj', 'AOG'::community_type, 'chapter'::ride_type, 'Bheri'::chapter_name,
   '2026-07-11', '2026-07-11', 'planned'::ride_status, 'chapter'::ride_priority,
   'AOG community ride in the Bheri region.',
   'AOG community ride covering the Bheri chapter region - Kohalpur and Nepalgunj - bringing together riders from across the western Terai.',
   20, ARRAY['aog', 'bheri', 'kohalpur', 'nepalgunj', 'community']::text[],
   false, false),
  ('CULT Ride - Ilam & Birtamode', 'cult-ride-ilam-birtamode', 'CULT'::community_type, 'cult'::ride_type, 'Mechi'::chapter_name,
   '2026-07-18', '2026-07-18', 'planned'::ride_status, 'chapter'::ride_priority,
   'CULT eastern Nepal ride through Ilam tea estates and Birtamode.',
   'CULT lifestyle ride through the lush tea estates of Ilam and the border town of Birtamode in eastern Nepal.',
   20, ARRAY['cult', 'ilam', 'birtamode', 'eastern', 'tea', 'mechi']::text[],
   false, false),
  ('AOG x CULT Overnight - Bagmati', 'aog-x-cult-overnight-bagmati', 'AOGxCULT'::community_type, 'overnight'::ride_type, 'Bagmati'::chapter_name,
   '2026-07-24', '2026-07-25', 'planned'::ride_status, 'national'::ride_priority,
   'Joint AOG and CULT overnight ride in the Bagmati region.',
   'A collaborative overnight ride bringing together AOG and CULT riders for a two-day journey through the Bagmati province. Camping, camaraderie, and shared roads.',
   30, ARRAY['aog', 'cult', 'overnight', 'bagmati', 'joint']::text[],
   false, false),
  ('AOG Ride - Mahendranagar', 'aog-ride-mahendranagar', 'AOG'::community_type, 'chapter'::ride_type, 'Mahakali'::chapter_name,
   '2026-08-08', '2026-08-08', 'planned'::ride_status, 'chapter'::ride_priority,
   'AOG chapter ride to far-western Mahendranagar.',
   'AOG ride to Mahendranagar, the gateway city of Sudurpashchim province on the western border, covering the Mahakali chapter territory.',
   20, ARRAY['aog', 'mahendranagar', 'far-west', 'sudurpashchim']::text[],
   false, false),
  ('CULT Ride - Janakpur', 'cult-ride-janakpur', 'CULT'::community_type, 'cult'::ride_type, 'Narayani'::chapter_name,
   '2026-08-15', '2026-08-15', 'planned'::ride_status, 'chapter'::ride_priority,
   'CULT cultural ride to Janakpur, the city of Mithila art.',
   'CULT lifestyle ride to Janakpur - Nepal''s cultural capital of the Madhesh, famous for Mithila art, the Janaki Mandir, and its rich heritage.',
   20, ARRAY['cult', 'janakpur', 'culture', 'mithila', 'madhesh']::text[],
   false, false),
  ('AOG Ride - Chitwan (August)', 'aog-ride-chitwan-august', 'AOG'::community_type, 'chapter'::ride_type, 'Narayani'::chapter_name,
   '2026-08-22', '2026-08-22', 'planned'::ride_status, 'chapter'::ride_priority,
   'AOG Narayani chapter ride through Chitwan.',
   'AOG chapter ride through Chitwan district - home to the Chitwan National Park, Narayani river, and the thriving chapter community.',
   20, ARRAY['aog', 'chitwan', 'narayani', 'jungle']::text[],
   false, false),
  ('AOG Community Ride - Biratnagar', 'aog-community-ride-biratnagar', 'AOG'::community_type, 'chapter'::ride_type, 'Koshi'::chapter_name,
   '2026-09-05', '2026-09-05', 'planned'::ride_status, 'chapter'::ride_priority,
   'AOG Koshi chapter community ride in Biratnagar.',
   'AOG community ride in Biratnagar, the industrial capital of eastern Nepal and home of the Koshi chapter.',
   20, ARRAY['aog', 'biratnagar', 'koshi', 'eastern', 'community']::text[],
   false, false),
  ('Mustang Biking Festival - AOG x CULT Marquee 2026', 'mustang-biking-festival-aog-x-cult-marquee-2026', 'AOGxCULT'::community_type, 'marquee'::ride_type, 'Gandaki'::chapter_name,
   '2026-09-15', '2026-09-21', 'confirmed'::ride_status, 'marquee'::ride_priority,
   'The crown jewel of 2026 - 7-day marquee expedition to Upper Mustang.',
   'The flagship AOG x CULT marquee expedition of 2026 - a 7-day biking festival through the mythical Upper Mustang. Routes cover Pokhara to Jomsom, Kagbeni, Chuksang, and Lo Manthang. Restricted area permits, Tibetan-influenced culture, high-altitude desert, and the raw beauty of the Forbidden Kingdom. The premier riding event of the year.',
   60, ARRAY['marquee', 'mustang', 'expedition', 'festival', 'gandaki', 'high-altitude', 'aog', 'cult']::text[],
   true, false),
  ('AOG Chapter Ride - Bagmati (October)', 'aog-chapter-ride-bagmati-october', 'AOG'::community_type, 'chapter'::ride_type, 'Bagmati'::chapter_name,
   '2026-10-10', '2026-10-10', 'planned'::ride_status, 'chapter'::ride_priority,
   'Monthly AOG Bagmati chapter ride for October.',
   'Monthly AOG chapter ride for Bagmati members during the post-monsoon season - clear skies, smooth roads, and peak riding weather.',
   20, ARRAY['aog', 'bagmati', 'chapter', 'october']::text[],
   false, false),
  ('Ride Back Home with TVS - National', 'ride-back-home-with-tvs-national', 'AOGxCULT'::community_type, 'overnight'::ride_type, 'Bagmati'::chapter_name,
   '2026-10-17', '2026-10-18', 'planned'::ride_status, 'national'::ride_priority,
   'National multi-city ride: Kathmandu to Birtamode, Chitwan, and Nepalgunj simultaneously.',
   'A landmark TVS Nepal national event running simultaneously across three corridors: Kathmandu to Birtamode (East), Kathmandu to Chitwan, and Kathmandu to Nepalgunj (via Pokhara/Butwal). Hundreds of TVS riders across AOG and CULT communities riding home for the festive season.',
   30, ARRAY['tvs', 'national', 'multi-city', 'dashain', 'birtamode', 'chitwan', 'nepalgunj']::text[],
   false, false),
  ('AOG x CULT Ride - October (TBD)', 'aog-x-cult-ride-october-tbd', 'AOGxCULT'::community_type, 'chapter'::ride_type, 'Bagmati'::chapter_name,
   '2026-10-31', '2026-10-31', 'tentative'::ride_status, 'chapter'::ride_priority,
   'Potential joint AOG and CULT ride - date to be confirmed.',
   'A possible joint AOG x CULT ride planned for end of October. Details and location to be confirmed based on feasibility and chapter availability.',
   20, ARRAY['aog', 'cult', 'tentative', 'october']::text[],
   false, false),
  ('Motosoul Marquee - Kathmandu to Goa', 'motosoul-marquee-kathmandu-to-goa', 'AOGxCULT'::community_type, 'marquee'::ride_type, 'Bagmati'::chapter_name,
   '2026-12-01', '2026-12-15', 'planned'::ride_status, 'marquee'::ride_priority,
   'Epic 15-day AOG x CULT marquee ride from Kathmandu to Goa, India.',
   'Motosoul - the most ambitious AOG x CULT marquee ride to date. A 15-day cross-border expedition from Kathmandu to Goa, covering thousands of kilometres through Nepal and India. This is the ultimate TVS Nepal riding event of 2026: an international marquee journey celebrating motorcycle culture, brotherhood, and the open road. Preparation begins mid-November with community induction rides.',
   60, ARRAY['marquee', 'motosoul', 'kathmandu', 'goa', 'india', 'international', '15-day']::text[],
   true, false),
  ('AOG x CULT Christmas CSR Ride - Bagmati', 'aog-x-cult-christmas-csr-ride-bagmati', 'AOGxCULT'::community_type, 'chapter'::ride_type, 'Bagmati'::chapter_name,
   '2026-12-25', '2026-12-25', 'planned'::ride_status, 'chapter'::ride_priority,
   'Christmas-themed community service ride in Bagmati.',
   'A special Christmas-themed CSR (Community Service) ride bringing together AOG and CULT riders in Bagmati for a day of giving back to the community while celebrating the festive season on two wheels.',
   20, ARRAY['aog', 'cult', 'christmas', 'csr', 'bagmati', 'community-service']::text[],
   false, false),
  ('CULT Ride - Pokhara (January 2027)', 'cult-ride-pokhara-january-2027', 'CULT'::community_type, 'cult'::ride_type, 'Gandaki'::chapter_name,
   '2027-01-09', '2027-01-09', 'planned'::ride_status, 'chapter'::ride_priority,
   'CULT lifestyle and exploration ride to Pokhara.',
   'CULT ride to Pokhara - Nepal''s tourism capital nestled beside Phewa Lake with views of the Annapurna range. A perfect winter CULT destination ride.',
   20, ARRAY['cult', 'pokhara', 'gandaki', 'lakeside', 'lifestyle']::text[],
   false, false),
  ('AOG Chapter Ride - Lumbini (January 2027)', 'aog-chapter-ride-lumbini-january-2027', 'AOG'::community_type, 'chapter'::ride_type, 'Lumbini'::chapter_name,
   '2027-01-16', '2027-01-16', 'planned'::ride_status, 'chapter'::ride_priority,
   'AOG Lumbini chapter ride for January.',
   'AOG monthly chapter ride covering the Lumbini province, with routes through the spiritual and cultural heartland of western Nepal.',
   20, ARRAY['aog', 'lumbini', 'chapter', 'january']::text[],
   false, false),
  ('AOG x CULT Overnight Carnival - Multi-City', 'aog-x-cult-overnight-carnival-multi-city', 'AOGxCULT'::community_type, 'overnight'::ride_type, 'Bagmati'::chapter_name,
   '2027-01-22', '2027-01-23', 'planned'::ride_status, 'national'::ride_priority,
   'Joint overnight carnival across Pokhara, Chitwan, and Kathmandu.',
   'A joint AOG x CULT overnight carnival event running simultaneously across three major cities - Pokhara, Chitwan, and Kathmandu. A celebration of the riding community with overnight stays, group activities, and chapter meetups.',
   30, ARRAY['aog', 'cult', 'overnight', 'carnival', 'pokhara', 'chitwan', 'kathmandu', 'multi-city']::text[],
   false, false),
  ('AOG Ride - Birgunj', 'aog-ride-birgunj', 'AOG'::community_type, 'chapter'::ride_type, 'Narayani'::chapter_name,
   '2027-01-30', '2027-01-30', 'planned'::ride_status, 'chapter'::ride_priority,
   'AOG central region chapter ride to Birgunj.',
   'AOG chapter ride to Birgunj - the major trade city on the Nepal-India border in Narayani province, connecting central Nepal chapters.',
   20, ARRAY['aog', 'birgunj', 'narayani', 'central', 'terai']::text[],
   false, false),
  ('AOG CSR Ride (February 2027)', 'aog-csr-ride-february-2027', 'AOG'::community_type, 'chapter'::ride_type, 'Bagmati'::chapter_name,
   '2027-02-13', '2027-02-13', 'planned'::ride_status, 'local'::ride_priority,
   'AOG community service and social responsibility ride.',
   'Annual AOG CSR (Community Service Responsibility) ride - riders come together to give back through social initiatives, raising awareness and contributing to communities along the route.',
   20, ARRAY['aog', 'csr', 'community-service', 'social']::text[],
   false, false),
  ('AOG x CULT Chapter Ride - Surkhet', 'aog-x-cult-chapter-ride-surkhet', 'AOGxCULT'::community_type, 'chapter'::ride_type, 'Bheri'::chapter_name,
   '2027-02-20', '2027-02-20', 'planned'::ride_status, 'chapter'::ride_priority,
   'Joint AOG and CULT chapter ride to Surkhet, Karnali.',
   'Joint AOG x CULT chapter ride to Surkhet - the emerging hub of Karnali province. Riders from across the Bheri region join for a collaborative chapter event.',
   20, ARRAY['aog', 'cult', 'surkhet', 'karnali', 'bheri', 'chapter']::text[],
   false, false),
  ('CULT Ride - Mechi (February 2027)', 'cult-ride-mechi-february-2027', 'CULT'::community_type, 'cult'::ride_type, 'Mechi'::chapter_name,
   '2027-02-27', '2027-02-27', 'planned'::ride_status, 'chapter'::ride_priority,
   'CULT eastern border ride in the Mechi chapter region.',
   'CULT lifestyle ride through the Mechi chapter area - the eastern tip of Nepal bordering India''s West Bengal, with lush forests, tea gardens, and the Mechi river.',
   20, ARRAY['cult', 'mechi', 'eastern', 'border', 'koshi']::text[],
   false, false),
  ('AOG Chapter Ride - Chitwan (March 2027)', 'aog-chapter-ride-chitwan-march-2027', 'AOG'::community_type, 'chapter'::ride_type, 'Narayani'::chapter_name,
   '2027-03-13', '2027-03-13', 'planned'::ride_status, 'chapter'::ride_priority,
   'AOG Narayani chapter ride through Chitwan.',
   'AOG chapter ride through Chitwan as spring riding season begins - perfect weather along the Narayani corridor.',
   20, ARRAY['aog', 'chitwan', 'narayani', 'march']::text[],
   false, false),
  ('CULT Ride - Mahendranagar & Dhangadhi', 'cult-ride-mahendranagar-dhangadhi', 'CULT'::community_type, 'cult'::ride_type, 'Mahakali'::chapter_name,
   '2027-03-20', '2027-03-20', 'planned'::ride_status, 'chapter'::ride_priority,
   'CULT far-western ride through Mahendranagar and Dhangadhi.',
   'CULT exploration ride through the far-western corridor - Mahendranagar and Dhangadhi, covering the Mahakali chapter territory along Sudurpashchim province.',
   20, ARRAY['cult', 'mahendranagar', 'dhangadhi', 'far-west', 'sudurpashchim']::text[],
   false, false),
  ('AOG x CULT Year-Close Ride - Kathmandu', 'aog-x-cult-year-close-ride-kathmandu', 'AOGxCULT'::community_type, 'overnight'::ride_type, 'Bagmati'::chapter_name,
   '2027-03-26', '2027-03-27', 'planned'::ride_status, 'national'::ride_priority,
   'Year-close joint AOG x CULT overnight ride in Kathmandu.',
   'The final joint AOG x CULT overnight ride of the season - a Kathmandu-based celebration bringing together riders from all chapters for a memorable year-close event before the new Nepali year.',
   30, ARRAY['aog', 'cult', 'kathmandu', 'bagmati', 'year-close', 'overnight']::text[],
   false, false)

ON CONFLICT (slug) DO UPDATE SET
  title             = EXCLUDED.title,
  short_description = EXCLUDED.short_description,
  description       = EXCLUDED.description,
  start_date        = EXCLUDED.start_date,
  end_date          = EXCLUDED.end_date,
  status            = EXCLUDED.status,
  priority          = EXCLUDED.priority,
  community         = EXCLUDED.community,
  ride_type         = EXCLUDED.ride_type,
  chapter           = EXCLUDED.chapter,
  expected_riders   = EXCLUDED.expected_riders,
  tags              = EXCLUDED.tags,
  is_featured       = EXCLUDED.is_featured;

-- 28 rides inserted/updated